### ISSUE TITLE
Edit button doesn't work

### ISSUE THREAD

**Issue by howff** [EOX-A/QgsWcsClient2#12]
I can create new server connections and delete them but I cannot edit one:
the changes made don't appear to be saved when I press OK.
Version 0.3

**Comment by eox-cs1** [comment]
Hi hwoff, 
could you please provide me with some more information. 
which Qgis version; which OS, are you using. Furthermore:
Start Qgis new. Then, in Qgis please start the python shell  -->  Menu-Plugins-Python Console; then start the WCSClient2 Plugin and run the above operations. 
Please send me the output from the console so I get some idea what is going on. 
regards
Christian

**Comment by howff** [comment]
qgis 2.14.14-essen in osgeo 11 (ubuntu)
The only output seems to be
IDX:  4
Editing: 4 -- [u't_1', u'http://w/w?'] -- Check: t_1

**Comment by eox-cs1** [comment]
Hey, 
OK, I could verify the problem with the Edit. 
I can give you a fast workaround:   when you edit a resource you need to also change the Name eg. add a space at the end. Then editing works. 
I have added this issue to my TODO list for the next release.

**Comment by eox-cs1** [comment]
this has been fixed with release 0.3.2
