### ISSUE TITLE
offered_crs is not defined

### ISSUE THREAD

**Issue by howff** [EOX-A/QgsWcsClient2#13]
When I connect to Rasdaman sample database and click GetCoverage for AverageChloro I get the error
NameError: global name 'offered_crs' is not defined (qgswcsclient2dialog.py 103 in new_function)

**Comment by eox-cs1** [comment]
Hi hwoff, 
could you please provide me with some more information. 
which Qgis version; which OS, are you using. Furthermore:
Start Qgis new. Then, in Qgis please start the python shell  -->  Menu-Plugins-Python Console; then start the WCSClient2 Plugin and run the above operations. 
Please send me the output from the console so I get some idea what is going on. 
regards
Christian

**Comment by howff** [comment]
That was the output from the console

**Comment by eox-cs1** [comment]
It looks like you forgot to paste the output ?

**Comment by howff** [comment]
? It's in the original issue report!

**Comment by eox-cs1** [comment]
I mean the full output, not just the last line.

**Comment by howff** [comment]
I tried it another six times and that is all I get. Nothing else.

**Comment by eox-cs1** [comment]
A typical output in the QGis Python Console would look like this:
Python Console 
Use iface to access QGIS API interface or Type help(iface) for more info
You choose:  OGC: WCS 2.0/EO-WCS 1.0 - Reference Implemetation (EOxServer) URL: http://ows.eox.at/cite/eoxserver/ows?
WCS-Version:  2.0.1
REQUEST:  http://ows.eox.at/cite/eoxserver/ows?service=WCS&request=GetCapabilities&sections=All
Selected Item:  MERIS_MGVI 2006-07-01T00:00:00Z 2010-09-30T23:59:59.990000Z 90.000000 180.000000 -90.000000 -180.000000 S
Selected EO-Series:  ['MERIS_MGVI']
REQUEST:  http://ows.eox.at/cite/eoxserver/ows?service=WCS&version=2.0.1&request=DescribeEOCoverageSet&eoID=MERIS_MGVI&containment=overlaps&count=10
Selected CoverageID:  ['L3_ENV_MER_MGVI_m__20070801_GLOB_SI_ESA']
REQUEST: http://ows.eox.at/cite/eoxserver/ows?service=WCS&version=2.0.1&request=GetCoverage&coverageid=L3_ENV_MER_MGVI_m__20070801_GLOB_SI_ESA&format=image/tiff&outputcrs=http://www.opengis.net/def/crs/EPSG/0/4326&interpolation=average

... and then somewhere would come the traceback for the error

**Comment by howff** [comment]
You choose: rasdaman URL: http://localhost:8080/rasdaman/ows/wcs2?
WCS-Version: 2.0.1
REQUEST: http://localhost:8080/rasdaman/ows/wcs2?service=WCS&request=GetCapabilities
Selected Item: 2017_11_15 C
Selected CoverageID: ['2017_11_15']
Then the error message is in the Python error window.

I have to admit I don't always get this error any more, sometimes I get other errors but I'll report them separately. (I've never successfully got anything at all to work, yet!) .

**Comment by eox-cs1** [comment]
Hey,  
could you please also post the output of the http://localhost:8080/rasdaman/ows/wcs2?service=WCS&request=GetCapabilities  request.

**Comment by howff** [comment]
[gc.txt](https://github.com/EOX-A/QgsWcsClient2/files/1488063/gc.txt)

**Comment by eox-cs1** [comment]
Hi howff, 
I had a look at your GetCapabilities.xml. The section for the CRS is missing. 
I.e. something along these lines should be there.
<wcs:Extension>
  <crs:CrsMetadata>
    <crs:crsSupported>http://www.opengis.net/def/crs/EPSG/0/4326</crs:crsSupported>
    <crs:crsSupported>http://www.opengis.net/def/crs/EPSG/0/3857</crs:crsSupported>
    <crs:crsSupported>http://www.opengis.net/def/crs/EPSG/0/3035</crs:crsSupported>
  </crs:CrsMetadata>
...

However, the QgsWcsClient2 has a fallback included for such a cases,  i.e. the 'offered_crs' it will be set to EPSG:4326 for cases where nor crs are provided. So I assume that there are also some other issues with the rasdaman installation (which is know to be very tricky).
Unfortunately I can't do much if I don't get at least the traceback messages providing a more detailed description and allowing the analysis of the error.
