### ISSUE TITLE
Getcoverage isnot working

### ISSUE THREAD

**Issue by polzader** [EOX-A/QgsWcsClient2#15]
I am using:
Ubuntu 14.04 LTS
QGIS 2.14.3 ESSEN
Connecting to WCS 2.0.1 server

Steps:
1 - Conect server WCS -> is ok
2 - Getcapabilities -> is ok
3 - describecoverage -> is ok
4 - getcoverage -> is not ok. When the plugin asks me to select the output directory it sticks and stops responding (show image tres.png)

Thanks Pablo

![dos](https://user-images.githubusercontent.com/8774758/36653065-9f688fe6-1a91-11e8-8dc4-53145567e757.png)
![tres](https://user-images.githubusercontent.com/8774758/36653066-9f91acf0-1a91-11e8-80c9-5405ed84138f.png)
![una](https://user-images.githubusercontent.com/8774758/36653067-9fb8fcd8-1a91-11e8-9eb5-467611c47d59.png)

**Comment by eox-cs1** [comment]
Hi Pablo, 
could you please first start the Python Console (MENU -> Plugins -> Python console) and then start the QgsWcsClient2 client and perform the above shown procedure. 
There should be some more detailed information printed in the Python Console.  Please provide me with this output,  which should help me to understand what/where the problem is. 
thanks
Christian

**Comment by eox-cs1** [comment]
Hi Pablo,
did you find the problem? What was it. It would be nice to here from you. 
Can I close this issue? 
regards
Christian

**Comment by polzader** [comment]
Ok. now is working! (below the log) . I just uninstall and re-install the add-on. I am using QGIS 2.18.
Thanks

Log file:
REQUEST:  http://domain/wcs?service=WCS&version=2.0.1&request=DescribeCoverage&coverageID=Sequia_Historico__Sequia_NDDI_9_h13v13
Selected CoverageID:  ['Sequia_Historico__Sequia_NDDI_9_h13v13']
REQUEST: http://domain/wcs?service=WCS&version=2.0.1&request=GetCoverage&coverageid=Sequia_Historico__Sequia_NDDI_9_h13v13&format=application/gml%2Bxml&outputcrs=http://www.opengis.net/def/crs/EPSG/0/4326&mediatype=multipart/related
GCov_result / HTTP-Code:  200
