### ISSUE TITLE
Wrong Select Sections in DescribeEOCoverageSet

### ISSUE THREAD

**Issue by vskorole** [EOX-A/QgsWcsClient2#16]
Requirement 55 /req/eowcs/describeEOCoverageSet-response-section-
coverageDescriptions:
If a DescribeEOCoverageSet request contains a sections parameter then a successful re-
sponse shall contain a wcs:CoverageDescriptions element if and only if the section
parameter list contains one of the values \u201c**CoverageDescriptions**\u201d or \u201cAll\u201d.
Requirement 56 /req/eowcs/describeEOCoverageSet-response-section-
datasetSeriesDescriptions:
If a DescribeEOCoverageSet request contains a sections parameter then a successful re-
sponse shall contain a eowcs:DatasetSeriesDescriptions element if and only if the
section parameter list contains one of the values \u201c**DatasetSeriesDescriptions**\u201d or \u201c**All**\u201d.

Current options: All, DataSeriesSummary, CoverageSummary

**Comment by eox-cs1** [comment]
Dear vskorole, 
the section parameter is only used in the GetCapabilities request, but not  in the DescribeEOCoverageSet requests. You can verify this if you open the python-console within QGis and then the QgsWcsClient2. 
The requests (and other selections) are then printed to the python-console.
I hope this answers your inquiry 
reagards
Christian

**Comment by vskorole** [comment]
Dear Christian,
Your answer is not quite good enough.
If you don’t use “sections” in the DescribeEOCoverageSet then why do you put checkboxes in the form?
In this case you confuse users and should remove checkboxes.

Slav Korolev
Work :  301-851-8339
Cell:      240-481-4003
Slav.korolev@nasa.gov<mailto:Slav.korolev@nasa.gov>
Vyacheslav.s.korolev@raytheon.com

**Comment by eox-cs1** [comment]
Dear vskorole, 
These checkboxes were added on a users-request. I didn't have them in the initial version. 
For me it was clear that the checkboxes on the GetCapabilities Tab only apply to the GetCapabilities. 
Sorry if that caused some misunderstanding.
regards 
Christian

**Comment by eox-cs1** [comment]
Dear vskorole,
this has now been fixed with release 0.3.2 (just gone online)

your input above didn't cover the actual bug causing the misbehaviour, but it pointed me in the right direction, so it was very helpful. 
Sorry for the overall delay with the fix, but I was busy with other things...
Christian
