### ISSUE TITLE
New WCS 2.0 available for testing 

### ISSUE THREAD

**Issue by HerzovanderWal** [EOX-A/QgsWcsClient2#18]
We would like to receive comments on the services and on the use of these services with QGIS and the QgsWcsClient2:
https://coverage.wetransform.eu/rws/hoogte_nl_1m/ows?SERVICE=WCS&ACCEPTVERSIONS=2.0.1&REQUEST=GetCapabilities
https://coverage.wetransform.eu/rws/hoogte_nl_1m/ows?SERVICE=WCS&VERSION=2.0.1&REQUEST=DescribeCoverage&COVERAGEID=hoogte_nl_1m

**Comment by eox-cs1** [comment]
Hi, 
I'm not sure what you expect from me. 
The QgsWcsClient2 contains a detailed Help section which explains its usage.
I have quickly tested you endpoin [https://coverage.wetransform.eu/rws/hoogte_nl_1m/ows?] t 2 weeks ago, and it worked for the DatasetSeries. Today I checked again, but there are no DatasetSeries available anymore. 
For Datasets (currently provided) it seems that it is not capable of handling interpolation requests. Please contact the rasdaman team for this issue.
If you open the "Python Console" (via Plugins Menu) prior to the QgsWcsClient2 plugin, you will see all the requests sent to your server by the QgsWcsClient2. You may them use them in any web-browser to narrow down any issues.

best regards

**Comment by HerzovanderWal** [comment]
Thank you Christian, That is are the result on my question that I'm looking for. Your comments on the availability are all ready passed through on the provider(s). And I got some help from you using the extremely powerfulle capabilities of this service type. I wonder if there is a youtube like instruction on using the QgsWcsClient2 extension. What would you recommend. If there is not can I ask you to film youre actions and share them?

**Comment by eox-cs1** [comment]
Hey,
The is no such thing like a YouTube video, and I do not intend to create one for the QgsWcsClient2.
I recommend that you study/read the Help available inside the QgsWcsClient2. 
best regards

**Comment by HerzovanderWal** [comment]
Is ít possible that you help me to fill in the tab Process Coverage in te QGIS extension WCPS-client? From Rasdaman I got a service and a query. I filled in the information in the App. In orde to show what my strugle is I made the following screendumps. I expect a coverage. 
  
![WCS_connect_with_QGIS_WCPS_Client_0](https://user-images.githubusercontent.com/33277602/173016024-7e3a3439-07f8-48d9-a0ed-d073013cd0c8.png)
![WCS_connect_with_QGIS_WCPS_Client_1](https://user-images.githubusercontent.com/33277602/173016027-27f3d83a-74a5-4895-a267-d0c5461c173c.png)
![WCS_connect_with_QGIS_WCPS_Client_2](https://user-images.githubusercontent.com/33277602/173016031-110e119d-a1c6-4a10-b1f9-5554b0677b09.png)
![WCS_connect_with_QGIS_WCPS_Client_3](https://user-images.githubusercontent.com/33277602/173016019-7ccc9a2e-813b-4dcb-89d7-6430d22b642c.png)

**Comment by eox-cs1** [comment]
Hey, 
This WCPS Client has been created by rasdaman - you have to ask them for support. 
I have nothing to do with this development (actually its the first time I see it).
best regards
