### ISSUE TITLE
QGIS 3.x support?

### ISSUE THREAD

**Issue by misev** [EOX-A/QgsWcsClient2#19]
The plugin works mostly well with QGIS 2.x, but it seems to be incompatible with QGIS 3.x. Are there any plans to update it? I believe the migration is not too involved.

**Comment by eox-cs1** [comment]
The plugin is still in Python-2 and needs a migration to Python-3, to work with  QGIS 3.x. This also requires an upgrade for the GUIs to a newer version of Qt (which currently it's qt-4).
In general, the plan is to upgrade the plugin to work with  QGIS 3.x it but it a matter of time availability. 
If you are willing to help, you are more then welcome.

**Comment by misev** [comment]
Is there a plan to merge patch #20 and update the plugin?

**Comment by eox-cs1** [comment]
I have tried to run patch [#20](https://github.com/EOX-A/QgsWcsClient2/pull/20) but it is not working yet. 
It seems to me that it has just simply been translated with the automatic tools without further verification of its functionality. 
So a merge will not happen before its really working.

**Comment by misev** [comment]
As there was no interest here to update this plugin: I forked the repo [here](https://github.com/rasdaman/QgisWcs2Client), applied #20 and uploaded as a new plugin at https://plugins.qgis.org/plugins/QgisWcs2Client
